project_name: go-x1

release:
  disable: false
  draft: true
  prerelease: auto

builds:
  - id: darwin-amd64
    main: ./cmd/opera/main.go
    binary: x1
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    ldflags:
      - -s -w
      - -X github.com/Fantom-foundation/go-opera/cmd/opera/launcher.gitCommit={{ .ShortCommit }}
      - -X github.com/Fantom-foundation/go-opera/cmd/opera/launcher.gitDate={{ .CommitDate }}

  - id: darwin-arm64
    main: ./cmd/opera/main.go
    binary: x1
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    ldflags:
      - -s -w
      - -X github.com/Fantom-foundation/go-opera/cmd/opera/launcher.gitCommit={{ .ShortCommit }}
      - -X github.com/Fantom-foundation/go-opera/cmd/opera/launcher.gitDate={{ .CommitDate }}

  - id: linux-amd64
    main: ./cmd/opera/main.go
    binary: x1
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    ldflags:
      - -s -w -linkmode external -extldflags "-static"
      - -X github.com/Fantom-foundation/go-opera/cmd/opera/launcher.gitCommit={{ .ShortCommit }}
      - -X github.com/Fantom-foundation/go-opera/cmd/opera/launcher.gitDate={{ .CommitDate }}
    tags:
      - netgo
      - osusergo

  - id: linux-arm64
    main: ./cmd/opera/main.go
    binary: x1
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      - -s -w -linkmode external -extldflags "-static"
      - -X github.com/Fantom-foundation/go-opera/cmd/opera/launcher.gitCommit={{ .ShortCommit }}
      - -X github.com/Fantom-foundation/go-opera/cmd/opera/launcher.gitDate={{ .CommitDate }}
    tags:
      - netgo
      - osusergo

archives:
  -
    files:
      - COPYING.LESSER
      - README.md

snapshot:
  name_template: "{{ .Tag }}.next"

dockers:
  - image_templates:
      - ghcr.io/FairCrypto/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile.release
    use: buildx
    goarch: amd64
    ids:
      - linux-amd64
    build_flag_templates:
      - --platform=linux/amd64
    skip_push: false

  - image_templates:
      - ghcr.io/FairCrypto/{{ .ProjectName }}:{{ .Version }}-arm64
    dockerfile: Dockerfile.release
    use: buildx
    goarch: arm64
    ids:
      - linux-arm64
    build_flag_templates:
      - --platform=linux/arm64
    skip_push: false

docker_manifests:
  - name_template: gcr.io/FairCrypto/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/faircrypto/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/faircrypto/{{ .ProjectName }}:{{ .Version }}-arm64
    skip_push: false

  - name_template: gcr.io/FairCrypto/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/faircrypto/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/faircrypto/{{ .ProjectName }}:{{ .Version }}-arm64
    skip_push: auto
