---
name: Release
on:  # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
      # to be used by fork patch-releases ^^
      - 'v*.*.*-*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo tag_name=${TAG} >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

        run: |
          docker run \
          		--rm \
          		--privileged \
          		-e CGO_ENABLED=1 \
          		-e GITHUB_TOKEN \
              -e DOCKER_CONFIG \
          		-v /var/run/docker.sock:/var/run/docker.sock \
          		-v `pwd`:/go/src/$(PACKAGE_NAME) \
          		-w /go/src/$(PACKAGE_NAME) \
          		ghcr.io/goreleaser/goreleaser-cross:${GOLANG_CROSS_VERSION} \
          		--rm-dist --skip-validate
        env:
          PACKAGE_NAME: github.com/faircrypto/go-x1
          GOLANG_CROSS_VERSION: v1.18.3
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.prepare.outputs.tag_name }}
